// <auto-generated />
using System;
using FaleIngles.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaleIngles.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522124053_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaleIngles.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<int>("OrderInPhase")
                        .HasColumnType("integer")
                        .HasColumnName("order_in_phase");

                    b.Property<int>("Phase")
                        .HasColumnType("integer")
                        .HasColumnName("phase");

                    b.Property<string>("SituationContext")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("situation_context");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("FaleIngles.Domain.Entities.Phrase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Affirmative")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("affirmative");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("audio_url");

                    b.Property<string>("Interrogative")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("interrogative");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Negative")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("negative");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("phrases", (string)null);
                });

            modelBuilder.Entity("FaleIngles.Domain.Entities.UserProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompletedLessonIds")
                        .HasColumnType("text")
                        .HasColumnName("completed_lesson_ids");

                    b.Property<int>("CurrentStreakDays")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak_days");

                    b.Property<int>("DailyGoalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("daily_goal_minutes");

                    b.Property<bool>("IsPro")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pro");

                    b.Property<DateOnly>("LastStudyDate")
                        .HasColumnType("date")
                        .HasColumnName("last_study_date");

                    b.Property<string>("MasteredPhraseIds")
                        .HasColumnType("text")
                        .HasColumnName("mastered_phrase_ids");

                    b.Property<int>("TodayMinutesStudied")
                        .HasColumnType("integer")
                        .HasColumnName("today_minutes_studied");

                    b.Property<int>("TotalMinutesStudied")
                        .HasColumnType("integer")
                        .HasColumnName("total_minutes_studied");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_progresses", (string)null);
                });

            modelBuilder.Entity("FaleIngles.Domain.Entities.Phrase", b =>
                {
                    b.HasOne("FaleIngles.Domain.Entities.Lesson", null)
                        .WithMany("Phrases")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("FaleIngles.Domain.Entities.Word", "Words", b1 =>
                        {
                            b1.Property<Guid>("PhraseId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("GrammaticalType")
                                .HasColumnType("integer")
                                .HasColumnName("grammatical_type");

                            b1.Property<string>("RoleInPhrase")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("role_in_phrase");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("text");

                            b1.Property<string>("Translation")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("translation");

                            b1.HasKey("PhraseId", "Id");

                            b1.ToTable("words", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PhraseId");
                        });

                    b.Navigation("Words");
                });

            modelBuilder.Entity("FaleIngles.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Phrases");
                });
#pragma warning restore 612, 618
        }
    }
}
